-- Tabla para estadísticas cargadas desde Excel (modelo vertical)
create table if not exists public.estadisticas (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materias(id) on delete cascade,
  anio int not null,
  indicador text not null,
  valor numeric not null,
  created_at timestamptz not null default now()
);

create unique index if not exists estadisticas_materia_anio_indicador
  on public.estadisticas (materia_id, anio, indicador);
