-- Vincula docentes con materias (y opcionalmente comisión)
create table if not exists public.materias_docentes (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materias(id) on delete cascade,
  user_id uuid not null,
  comision text null,
  created_at timestamptz not null default now()
);

create unique index if not exists materias_docentes_unique
  on public.materias_docentes (materia_id, user_id, comision);
